### PR TITLE
Fix quotes

### PR DESCRIPTION
**Pull request by janosroden**
Hi, quote usage is fixed, tested with bash 4.2.46.

### CODE REVIEW

**Review by wdouglascampbell — COMMENTED** [review]
I hesitate to accept these changes as I was thinking that using the quotes would take care of unexpected situations where an unescaped character would confused BASH when it processed the line.  I also don't have any time to do any tests to see whether this is fine for some versions of BASH and not others (I have run into issues in the past where I made a changed and it worked on one server but not another because they had different versions of BASH running).

**Comment by janosroden** [comment]
When I started to use your project it just didn't work for me with bash 4.2. Now when I see the changes I'm really can't imagine how it worked for you. The problem is that you can't store multiple parameters in a string variable if you plan to allow a must-quote-character in one of them. You just can't quote them properly, you have to use arrays in these cases. The following snippet illustrates the problem:

```
$ echo $BASH_VERSION
3.2.57(1)-release
$ POSTDATA=" --data-urlencode 'apiuser=xxx'"
$ ls -l "$POSTDATA"
ls: cannot access ' --data-urlencode '\''apiuser=xxx'\''': No such file or directory
$ ls -l -- $POSTDATA
ls: cannot access '--data-urlencode': No such file or directory
ls: cannot access ''\''apiuser=xxx'\''': No such file or directory

$ echo $BASH_VERSION
4.4.12(1)-release
$ POSTDATA=" --data-urlencode 'apiuser=xxx'"
$ ls -l "$POSTDATA"
ls: cannot access ' --data-urlencode '\''apiuser=xxx'\''': No such file or directory
$ ls -l -- $POSTDATA
ls: cannot access '--data-urlencode': No such file or directory
ls: cannot access ''\''apiuser=xxx'\''': No such file or directory
```
As you can see bash didn't split the POSTDATA due to the quotes around it, which means your curl call got " --data-urlencode 'apiuser=xxx'" in a single parameter which leads to error.
And without quotes the single quotes are passed as the part of the parameter which is bad too.

Do you use this plugin nowadays without any problems? I do, but only with this fix.
Let me know if I convinced you, I'll resolve the conflicts then.

Cheers

**Comment by wdouglascampbell** [comment]
Thanks!  I am partially convinced by your example.  The issue with the double quotes around $POSTDATA was caused by my careless acceptance of pull request #6.  I never updated the script on my servers that use this and so I never saw that it didn't work.  I have actually been using an older version.

That being said I do successfully use the single quotes with the --data-urlencode parameter and I find numerous examples online showing others using either single quotes, double quotes and even without quotes like you are suggesting.  I again hesitate not to use the single quotes because they should allow for non-escaped characters.  

Your example indicates that that the single quotes are being passed as the parameter but your example actually does not match the way this is being handled inside the script.  The following better represents the method in the script:

```
$echo $BASH_VERSION
4.2.37(1)-release
$POSTDATA=" --data-urlencode 'apiuser=xxx'"
$mytest=`ls -l -- $POSTDATA` && echo $mytest
ls: cannot access --data-urlencode: No such file or directory
ls: cannot access 'apiuser=xxx': No such file or directory
```

So I think that if you submitted the changes for line 14, 24, 44, 119, 129, 149 and left out all of the others including the #set -x that you added in line 2 as that was just used for your debugging I believe.  

Note:  Lines 78, 79, 151 and 152 should remain the same as should line 114.  In the past I found that when using curl with URLs that had parameters it was safest to surround the URL and parameters with single quotes.  These lines accomplish this and I believe the reason I used eval here was because without it I ran into the issue of the single quotes being treated as part of the parameter instead of single quoting the URL.

**Comment by janosroden** [comment]
Your example is modified.. no single quotes in the error message at least, and I get different output:
```
$ echo $BASH_VERSION
4.4.12(1)-release
$ POSTDATA=" --data-urlencode 'apiuser=xxx'"
$ mytest=`ls -l -- $POSTDATA` && echo $mytest
ls: cannot access '--data-urlencode': No such file or directory
ls: cannot access ''\''apiuser=xxx'\''': No such file or directory
```
Which has the same quoted output as before.

"So I think that if you submitted the changes... " - then what?

I changed the order of curl options and the url because curl's synopsis is `curl [options] [URL...]`

About evals: `eval 'script'` and `script` is just the same thing if you don't use the benefits of the double evaluation (you don't in this case). Bash evaluates the script, no difference here.

"In the past I found that when using curl with URLs that had parameters it was safest to surround the URL and parameters with single quotes." - That's propably because the '&'. Bash treats it as the end of the command and runs it in the background.

Actually it's pretty easy to decide to accept this PR: try the script with and without this PR :)

**Comment by wdouglascampbell** [comment]
Okay.  I'll bite and give it a try.  Might not get to test it until tomorrow.

**Comment by wdouglascampbell** [comment]
FYI.  I ended up going ahead and testing and it worked fine.  Hopefully something doesn't jump out in the future due to these changes but I feel pretty good about them now.  Notice that I did make one more commit due to issue with grep returning an error.  My guess is that this rarely occurs but that the token that happened to get generated when I tested happened to start with a -A but since it happened I have also hopefully prevented that edge case from occurring in the future.

**Comment by janosroden** [comment]
Nice catch with the grep!
Thanks for the merge, cheers :)

**Pull request merged**
